/*
 * Decompiled with CFR 0.152.
 */
public interface i {
    public static final String[] a = new String[]{"WARNING: THIS OPTION REQUIRES YOUR HANDSET TO CONNECT ONLINE, CONTINUE?", "ATTENTION: CETTE OPTION N\u00c9CESSITE LA CONNEXION DU T\u00c9L\u00c9PHONE \u00c0 INTERNET, CONTINUER?", "ATTENZIOINE: QUESTA OPZIONE RICHIEDE CHE IL CELLULARE SI COLLEGHI ONLINE, CONTINUARE?", "WARNUNG: F\u00dcR DIESE OPTION MUSS DEIN HANDY EINE INTERNETVERBINDUNG HERSTELLEN, WEITER?", "ATENCI\u00d3N: ESTA OPCI\u00d3N REQUIERE QUE TU M\u00d3VIL SE CONECTE EN LINEA, \u00bfCONTINUAR?"};
    public static final String[] b = new String[]{"GET MORE GAMES", "PLUS DE JEUX", "ALTRI GIOCHI", "MEHR SPIELE", "MAS JUEGOS"};
    public static final String[][] c = new String[][]{{"START TRIAL", "LANCEZ LA D\u00c9MO", "INIZIA PROVA", "TEST STARTEN", "INICIAR LA DEMO"}, {"GET IT", "T\u00c9L\u00c9", "SCARICA", "HOL'S DIR", "DESCARGAR"}, {"START TRIAL", "LANCEZ LA D\u00c9MO", "INIZIA PROVA", "TEST STARTEN", "INICIAR LA DEMO"}, {"TRIAL OVER", "D\u00c9MO TERMIN\u00c9E", "FINE PROVA", "TESTZEIT VORBEI", "DEMO TERMINADA"}, {"GET THE GAME", "ACHETER LE JEU", "ACQUISTA GIOCO", "SPIEL KAUFEN", "COMPRAR JUEGO"}};
}

